- .gitignore
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/1)
> feat: add build script

- .gitignore
- README.md
- dapps/cross-space/network-config.json
- dapps/cross-space/package.json
- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/store/conflux.ts
- dapps/cross-space/src/store/currentBalance.ts
- dapps/cross-space/src/store/currentNetwork.ts
- dapps/cross-space/src/store/currentToken.ts
- package.json
- packages/common/modules/AuthConnectButton/index.tsx
- packages/common/package.json
- pnpm-workspace.yaml
- turbo.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/3)
> feat: alot

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/components/TokenList/judgeAddressValid.ts
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- packages/common/modules/AuthConnectButton/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/4)
> fix: can't click bug

- dapps/cross-space/src/modules/Core2ESpace/handleSubmit.ts
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/handleTransfer.ts
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- dapps/cross-space/src/store/currentBalance.ts
- dapps/cross-space/src/store/currentToken.ts
- packages/common/components/tools/Toast/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/5)
> fix: approve behavior

- dapps/cross-space/index.html
- dapps/cross-space/src/modules/ESpace2Core/handleWithdraw.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/7)
> fix: add global in window

- dapps/cross-space/vite.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/9)
> fix: disabled build minify

- dapps/cross-space/src/assets/input-close.svg
- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- packages/common/components/Input/index.css
- packages/common/components/tools/Toast/index.tsx
- packages/common/modules/Navbar/WalletConnector/ConnectorDropdown.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/13)
> fix: some ui/ux bug

- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/handleTransfer.ts
- dapps/cross-space/src/modules/ESpace2Core/handleWithdraw.ts
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/14)
> feat: eSpace add in Transfer status

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/components/TokenList/tokenListStore.ts
- dapps/cross-space/src/modules/ESpace2Core/handleTransfer.ts
- dapps/cross-space/src/modules/ESpace2Core/handleWithdraw.ts
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/15)
> fix: disabled switch currentToken while in withdraw

- dapps/cross-space/network-config.json
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
Remove CFX transfer limit while has withdrawable balance.
update CRC20CrossSpaceSideContract address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/17)
> fix: Remove CFX transfer limit while has withdrawable balance

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/modules/Core2ESpace/handleSubmit.ts
- dapps/cross-space/src/modules/ESpace2Core/handleTransfer.ts
- dapps/cross-space/src/modules/ESpace2Core/handleWithdraw.ts
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- packages/common/assets/error.svg
- packages/common/assets/success-blue.svg
- packages/common/assets/warning.svg
- packages/common/components/tools/Toast/index.tsx
- packages/common/modules/AuthConnectButton/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/18)
> feat: add type icon in showToast

- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- dapps/cross-space/src/store/currentBalance.ts
- dapps/cross-space/src/store/currentToken.ts
- packages/common/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/19)
> fix: can't withdraw cfx while metamask not install

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/20)
> fix: common token list item key && isCurrent check

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- packages/common/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/21)
> fix: dropdown scroll in small screen

- dapps/cross-space/network-config.json
- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/store/currentNetwork.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/22)
> feat: add mainnet config

- dapps/cross-space/network-config.json
- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/store/currentNetwork.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/23)
> Merge dev to Stage

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
- dapps/cross-space/src/components/TokenList/index.tsx
- dapps/cross-space/src/components/TokenList/judgeAddressValid.ts
- dapps/cross-space/src/modules/Core2ESpace/handleSubmit.ts
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/handleTransfer.ts
- dapps/cross-space/src/modules/ESpace2Core/handleWithdraw.ts
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- dapps/cross-space/src/store/currentBalance.ts
- dapps/cross-space/src/store/currentToken.ts
- packages/tsconfig/base.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/25)
> feat: change token symbol/name rule

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/27)
> feat: disabled tokenList dropdown while network not match

- dapps/cross-space/src/store/currentBalance.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/33)
> build test

- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- dapps/dapp-box/.env.development
- packages/common/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/34)
> fix: change dev env shuttle-flow url

- dapps/dapp-box/.env.development.local
- dapps/dapp-box/index.html
- dapps/shuttle-flow/src/pages/App.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/35)
> fix: global var

- dapps/dapp-box/.env.development
- dapps/dapp-box/.env.development.local
- dapps/dapp-box/.env.production
- dapps/dapp-box/src/main.tsx
- dapps/dapp-box/src/vite-env.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/36)
> fix: sf entry

- dapps/dapp-box/src/App.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/37)
> feat: change browser router to hash router

- dapps/dapp-box/src/App.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/38)
> fix: browserrouter

- dapps/dapp-box/src/modules/NavbarEnhance/ShuttleFlow/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/44)
> fix: add search params in shuttleflow navlink

- dapps/dapp-box/src/modules/Sidebar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/50)
> fix: set advert default open

- dapps/dapp-box/src/modules/Sidebar/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/51)
> style: add advert bg opacity

- dapps/dapp-box/src/modules/Sidebar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/52)
> style: confluxhub drawer expand button

- dapps/dapp-box/src/App.css
- dapps/shuttle-flow/src/pages/App.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/58)
> fix: fix bg color

- dapps/bsc-espace/src/modules/Send/ChainSelect.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/66)
> fix: close metamask error bug

- dapps/bsc-espace/src/modules/Send/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/67)
> Temporarily remove restrictions on buttons when liquidity is not enough

- dapps/bsc-espace/package.json
- dapps/bsc-espace/src/modules/Claim/depositStore.tsx
- dapps/cross-space/package.json
- dapps/dapp-box/package.json
- dapps/shuttle-flow/package.json
- packages/common/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/68)
> fix: claim list switch account bug

- dapps/bsc-espace/src/store/balance.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/69)
> fix: bsc-espace send max

- dapps/cross-space/src/modules/Core2ESpace/index.css
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/dapp-box/src/modules/ESpaceBridgeEnter/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/70)
> fix: cross-space metamask account input size

- dapps/bsc-espace/config.ts
- dapps/bsc-espace/package.json
- dapps/bsc-espace/src/modules/Claim/depositStore.tsx
- dapps/bsc-espace/src/modules/Claim/index.tsx
- dapps/bsc-espace/src/modules/Send/index.tsx
- dapps/cross-space/package.json
- dapps/cross-space/vite.config.ts
- dapps/dapp-box/package.json
- dapps/dapp-box/src/hooks/use-wallet/index.ts
- dapps/dapp-box/vite.config.ts
- dapps/shuttle-flow/package.json
- packages/common/components/List/index.tsx
- packages/common/modules/AuthConnectButton/index.tsx
- packages/common/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/71)
> bsc-espace: change claimList animation from 'zoom' to 'slideRight'

- dapps/bsc-espace/config.ts
- dapps/bsc-espace/src/components/TokenList/TokenListDropdown.tsx
- dapps/bsc-espace/src/components/TokenList/tokenListStore.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/72)
> bsc-espace: use token's symbol as key

- packages/common/modules/BalanceText/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/82)
> Airdrop: decimals bug

- dapps/airdrop/package.json
- dapps/bsc-espace/package.json
- dapps/bsc-espace/src/modules/Send/index.tsx
- dapps/cross-space/package.json
- dapps/cross-space/src/App.tsx
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/index.tsx
- dapps/cross-space/src/store/conflux.ts
- dapps/dapp-box/package.json
- dapps/dapp-box/src/App.tsx
- dapps/dapp-box/src/main.tsx
- dapps/shuttle-flow/package.json
- dapps/shuttle-flow/src/hooks/useFluentTip.js
- dapps/shuttle-flow/src/pages/App.js
- packages/common/components/tools/Toast/index.tsx
- packages/common/hooks/useFluentTip.ts
- packages/common/modules/BalanceText/index.tsx
- packages/common/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/84)
> adapt fluent2.0

- dapps/bsc-espace/src/store/balance.ts
- dapps/cross-space/src/store/currentBalance.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/91)
> fix: estimate

- dapps/shuttle-flow/src/pages/components/Web3ReactManager/index.js
- dapps/shuttle-flow/src/pages/components/useClaimNotification/index.js
- dapps/shuttle-flow/src/pages/components/useTransactionNotification/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/93)
> fix: shuttle-flow build

- dapps/cross-space/package.json
- dapps/dapp-box/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/95)
> fix: support fluent2.1 rc44

- packages/common/modules/AuthConnectButton/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/97)
> fix: build bug

- dapps/airdrop/package.json
- dapps/airdrop/vite.config.ts
- dapps/bsc-espace/package.json
- dapps/bsc-espace/vite.config.ts
- dapps/cross-space/index.html
- dapps/cross-space/package.json
- dapps/cross-space/vite.config.ts
- dapps/dapp-box/package.json
- dapps/dapp-box/src/hooks/useCurrentDapp.ts
- dapps/dapp-box/vite.config.ts
- packages/common/package.json
- packages/common/utils/Contract.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/100)
> fix: build

- dapps/airdrop/src/modules/ClaimableList/index.tsx
- dapps/bsc-espace/config.ts
- dapps/bsc-espace/src/components/TokenList/TokenListDropdown.tsx
- dapps/bsc-espace/src/modules/Claim/PeggedModal.tsx
- dapps/bsc-espace/src/modules/Claim/index.tsx
- dapps/bsc-espace/src/modules/Redeem/index.tsx
- dapps/bsc-espace/src/modules/Send/index.tsx
- packages/common/components/showPopup/Modal/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/101)
> fix: espace-bsc PeggedModal continue button

- dapps/dapp-box/vite.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/102)
> tmp open sourcemap

- dapps/dapp-box/vite.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/103)
> fix: disabled minify

- dapps/dapp-box/vite.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/104)
> fix: delete hub base url

- dapps/cross-space/src/modules/Core2ESpace/handleSubmit.ts
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/handleWithdraw.ts
- dapps/dapp-box/src/modules/ESpaceBridgeEnter/index.tsx
- packages/common/modules/AuthConnectButton/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/105)
> fix: Fluent host MetaMask Bug

- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/108)
> fix: Conflux Hydra network config

- dapps/governance/src/components/TipModal/index.tsx
- dapps/governance/src/modules/Vote/Proposals/Pagination.tsx
- dapps/governance/src/modules/Vote/Proposals/index.css
- dapps/governance/src/modules/Vote/Proposals/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/111)
> style: fix some style

- dapps/governance/src/store/proposalList.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/113)
> fix: governance proposalDetail should abandon old fetchRes

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/117)
> fix: only-allow

- dapps/governance/src/store/contracts.ts
- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/118)
> fix: https

- dapps/dapp-box/src/App.tsx
- dapps/dapp-box/src/main.tsx
- dapps/governance/src/modules/Vote/Proposals/Pagination.tsx
- dapps/governance/src/modules/Vote/index.tsx
- dapps/governance/src/store/proposalList.ts
- dapps/governance/src/store/rewardInterestRate.ts
- packages/common/components/Input/index.tsx
- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/121)
> feat: support 8888 branch

- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/125)
> fix: change 8888 domain

- dapps/governance/src/modules/Dashboard/Lock/index.tsx
- dapps/governance/src/modules/Dashboard/Unstake/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.css
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/MathTex.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/VotingResult.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/126)
> Governance

- dapps/governance/src/modules/Dashboard/Lock/Slider/index.tsx
- dapps/governance/src/modules/Dashboard/Lock/handleLock.ts
- dapps/governance/src/store/lockDays&blockNumber.ts
- packages/common/components/Input/index.tsx
- packages/common/utils/time.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/128)
> fix-governance: net8888 lock BlockNumber

- dapps/governance/src/store/rewardInterestRate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/130)
> fix: dao vote start blockNumber

- dapps/dapp-box/src/App.tsx
- dapps/dapp-box/src/modules/Sidebar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/135)
> feat-Payment: add keyboard switch

- dapps/payment/package.json
- dapps/payment/src/components/Number/index.tsx
- dapps/payment/src/contracts/constants.ts
- dapps/payment/src/contracts/multicall.json
- dapps/payment/src/modules/Common/APIKey/index.tsx
- dapps/payment/src/modules/Common/APP/index.tsx
- dapps/payment/src/modules/Common/Deposit/index.tsx
- dapps/payment/src/modules/Common/Refund/index.tsx
- dapps/payment/src/modules/Common/Withdraw/index.tsx
- dapps/payment/src/modules/Consumer/APPs/index.tsx
- dapps/payment/src/modules/Consumer/PaidAPPs/index.tsx
- dapps/payment/src/modules/Provider/APPs/Create.tsx
- dapps/payment/src/modules/Provider/APPs/index.tsx
- dapps/payment/src/modules/Provider/Users/Airdrop.tsx
- dapps/payment/src/modules/index.tsx
- dapps/payment/src/store/index.ts
- dapps/payment/src/utils/columns/APPs.tsx
- dapps/payment/src/utils/columns/users.tsx
- dapps/payment/src/utils/constants.ts
- dapps/payment/src/utils/index.ts
- dapps/payment/src/utils/request.ts
- dapps/payment/src/utils/types.ts
- packages/common/modules/Navbar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/137)
> feat: sync payment

- dapps/payment/src/utils/request.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/138)
> fix: fixed global await issue

- dapps/payment/src/modules/Common/APP/APIs.tsx
- dapps/payment/src/modules/Common/APP/Create.tsx
- dapps/payment/src/modules/Common/APP/Delete.tsx
- dapps/payment/src/modules/Common/APP/index.tsx
- dapps/payment/src/modules/Common/Deposit/index.tsx
- dapps/payment/src/modules/Consumer/PaidAPPs/index.tsx
- dapps/payment/src/modules/Provider/APPs/Create.tsx
- dapps/payment/src/utils/columns/resources.tsx
- dapps/payment/src/utils/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/140)
> payment-feat: fixed bugs

- dapps/payment/package.json
- dapps/payment/src/modules/Common/APIKey/index.tsx
- dapps/payment/src/utils/request.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/145)
> payment-feat: update sign api key

- dapps/dapp-box/src/App.tsx
- dapps/dapp-box/src/modules/ESpaceBridgeEnter/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/146)
> hotfix: bsc-espace-cfx url typo

- dapps/dapp-box/src/App.tsx
- dapps/governance/src/App.css
- dapps/governance/src/components/Cell/index.tsx
- dapps/governance/src/components/Panel/index.tsx
- dapps/governance/src/contracts/paramsControl.json
- dapps/governance/src/modules/Dashboard/Lock/LockModal.tsx
- dapps/governance/src/modules/Dashboard/Lock/Slider/index.tsx
- dapps/governance/src/modules/Dashboard/Lock/index.tsx
- dapps/governance/src/modules/Dashboard/Stake/index.tsx
- dapps/governance/src/modules/Dashboard/Unstake/index.tsx
- dapps/governance/src/modules/Vote/Proposals/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/VotingResult.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/handleCastVotes.ts
- dapps/governance/src/modules/Vote/RewardInterestRate/index.tsx
- dapps/governance/src/modules/Vote/index.tsx
- dapps/governance/src/store/contracts.ts
- dapps/governance/src/store/rewardInterestRate.ts
- packages/common/utils/fetchChain.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/148)
> feat: governance vote Effective voting rights

- dapps/pos/src/components/CheckBox/index.tsx
- dapps/pos/src/modules/guide/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/150)
> refactor: pos checkbox

- dapps/bridge/src/components/Select/Dropdown.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/152)
> fix: bridge commonToken

- dapps/bridge/src/modules/index.tsx
- dapps/dapp-box/src/App.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/153)
> feat(bridge): Link to shuttleflow and eSpace Bridge

- dapps/bridge/src/modules/data.ts
- dapps/dapp-box/src/modules/Sidebar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/154)
> fix(bridge): core-espace add cfx

- dapps/bridge/src/modules/data.ts
- dapps/bridge/src/modules/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/155)
> fix(bridge): shuttleflow typo

- dapps/payment/src/modules/Provider/APP/CreateCard.tsx
- dapps/payment/src/modules/Provider/APPs/Create.tsx
- dapps/payment/src/utils/constants.ts
- dapps/payment/src/utils/index.ts
- dapps/payment/src/utils/request.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/159)
> feat: sync web3pay

- dapps/governance/src/store/rewardInterestRate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/161)
> fix: change mainnet start

- dapps/governance/src/modules/Vote/RewardInterestRate/VotingResult.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/163)
> fix: round = 1 hidden Effective voting rights

- dapps/governance/src/modules/Vote/RewardInterestRate/VotingResult.tsx
- dapps/governance/src/store/rewardInterestRate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/164)
> feat: round = 1 hidden Effective voting rights

- dapps/payment/src/modules/Common/APIKey/index.tsx
- dapps/payment/src/modules/Common/Deposit/index.tsx
- dapps/payment/src/modules/Common/PurchaseSubscription/index.tsx
- dapps/payment/src/modules/Common/Refund/index.tsx
- dapps/payment/src/modules/Common/Withdraw/index-copy.tsx
- dapps/payment/src/modules/Common/Withdraw/index.tsx
- dapps/payment/src/modules/Consumer/APPs/index.tsx
- dapps/payment/src/modules/Consumer/PaidAPPs/index.tsx
- dapps/payment/src/modules/Provider/APPs/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/169)
> payment-feat: update button style

- dapps/bridge/src/modules/index.tsx
- dapps/governance/src/modules/Dashboard/index.tsx
- dapps/shuttle-flow/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/170)
> fix: lock shuttleflow rc-util

- dapps/governance/src/modules/Dashboard/Lock/index.tsx
- dapps/shuttle-flow/src/components/Tooltip/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/173)
> fix: shuttleflow

- dapps/dapp-box/src/App.tsx
- dapps/dapp-box/src/modules/Sidebar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/178)
> fix: shuttleflow history menu

- dapps/payment/src/modules/Provider/APPs/index.tsx
- dapps/payment/src/utils/request.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/184)
> fix: fixed web3pay console log error

- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/187)
> feat: add dev-internal to Networks config

- dapps/payment/package.json
- dapps/payment/src/modules/Provider/APP/CreateCard.tsx
- dapps/payment/src/utils/constants.ts
- dapps/payment/src/utils/tokens.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/188)
> payment-feat: add mainnet contract address

- dapps/dapp-box/src/App.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/190)
> payment-feat: remove web3pay entry condition

- dapps/payment/src/modules/Common/PurchaseSubscription/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/196)
> payment-fix: #3rxhpwf

- dapps/payment/src/modules/Provider/APP/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/197)
> payment-fix: fixed provider tab issue

- dapps/payment/src/modules/Common/APP/Detail.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/198)
> payment-fix: #3rxtecy

- dapps/payment/src/utils/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/199)
> payment-fix: fixed connect wallet issue

- dapps/payment/src/modules/Common/Deposit/index.tsx
- dapps/payment/src/modules/Common/PurchaseSubscription/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/200)
> payment-fix: #3t38u0d

- dapps/payment/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/202)
> feat: release web3pay v1.1.0

- dapps/pos/src/modules/Guide/index.tsx
- dapps/pos/src/modules/Increase/handleStakeAndUnstake.ts
- dapps/pos/src/modules/Register/index.tsx
- dapps/pos/src/modules/guide/index.tsx
- dapps/pos/src/modules/index.tsx
- dapps/pos/src/modules/register/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/207)
> fix: pos stake|unstake bug

- dapps/pos/src/modules/Guide/index.tsx
- dapps/pos/src/modules/guide/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-dapps/208)
> fix: Pos GuidePage navigate

- dapps/bridge/src/modules/data.ts
- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/211)
> fix: shuttleflow stage link

- dapps/dapp-box/src/modules/Sidebar/index.tsx
- dapps/governance/src/components/TipModal/index.tsx
- dapps/pos/src/modules/Retired/RetiredCountDown.tsx
- dapps/pos/src/modules/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/215)
> fix: pos router && countdown

- dapps/pos/src/store/pos.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/220)
> fix: pos totalInterest unit

- dapps/bridge/src/modules/data.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/223)
> feat: bridge add eSpace-core-bsc route

- dapps/bridge/src/modules/data.ts
- dapps/pos/src/store/pos.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/224)
> Merge dev into stage

- dapps/governance/src/store/rewardInterestRate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/229)
> fix: governance vote

- dapps/bsc-espace/src/modules/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/236)
> feat: add faucet tip

- dapps/bsc-espace/src/modules/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/238)
> feat: change faucet ui

- dapps/payment/src/modules/Consumer/APP/SubscriptionInfo.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/240)
> payment: add $ to price

- dapps/cross-space/src/components/TokenList/tokenListStore.ts
- dapps/cross-space/src/modules/Core2ESpace/handleSubmit.ts
- dapps/cross-space/src/modules/Core2ESpace/index.tsx
- dapps/cross-space/src/modules/ESpace2Core/handleTransfer.ts
- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- dapps/cross-space/src/store/currentBalance.ts
- dapps/cross-space/src/store/currentToken.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/244)
> fix: cross-space decimal

- dapps/cross-space/src/store/currentBalance.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/254)
> fix: cfx maxAvailableBalance bug

- dapps/bsc-espace/config.ts
- dapps/bsc-espace/src/modules/Send/ChainSelect.tsx
- dapps/dapp-box/src/modules/Sidebar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/256)
> fix: shuttle-flow menu

- dapps/bridge/src/modules/data.ts
- dapps/bridge/src/modules/index.tsx
- dapps/bsc-espace/config.ts
- dapps/bsc-espace/src/modules/index.tsx
- dapps/cross-space/src/modules/index.tsx
- dapps/dapp-box/src/App.tsx
- dapps/dapp-box/src/modules/ESpaceBridgeEnter/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/257)
> fix: change bridge enter

- dapps/dapp-box/src/App.css
- dapps/dapp-box/src/main.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/262)
> feat: fix window-zoom

- dapps/cross-space/src/modules/ESpace2Core/index.tsx
- dapps/dapp-box/src/modules/Sidebar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/265)
> fix: default normal mode

- dapps/shuttle-flow/src/constants/contractConfig.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/264)
> chore: update testnet contract addresses

- dapps/shuttle-flow/src/constants/chainConfig.js
- dapps/shuttle-flow/src/pages/components/useTransactionNotification/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/271)
> Sf rebranding

- dapps/shuttle-flow/src/pages/App.js
- dapps/shuttle-flow/src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/274)
> feat: zoom

- dapps/shuttle-flow/public/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/276)
> fix: modify the bg

- dapps/shuttle-flow/src/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/277)
> fix: overflow

- dapps/shuttle-flow/public/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/278)
> fix: video

- dapps/shuttle-flow/public/index.html
- dapps/shuttle-flow/src/components/StepNavigation/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/280)
> fix: step progress color

- dapps/shuttle-flow/src/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/281)
> fix: input placeholder color

- dapps/shuttle-flow/src/pages/components/Header/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/282)
> feat: add faq

- dapps/shuttle-flow/public/index.html
- dapps/shuttle-flow/src/pages/components/Header/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/283)
> feat: replace background

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/285)
> remove preinstall only-allow yarn

- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/290)
> fix: http -> https

- dapps/governance/src/contracts/governance.json
- dapps/governance/src/modules/Dashboard/Pos/LockModal.tsx
- dapps/governance/src/modules/Dashboard/Pos/index.tsx
- dapps/governance/src/modules/Dashboard/Statistics/index.tsx
- dapps/governance/src/modules/Vote/Proposals/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.css
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/VotingResult.tsx
- dapps/governance/src/store/contracts.ts
- dapps/governance/src/store/lockDays&blockNumber.ts
- dapps/governance/src/store/proposalList.ts
- packages/common/components/Popup/Popup.tsx
- packages/common/utils/time.ts
-Change gov contract to support description field
-Fix total balance calculation
-Modal scroll bar
-Some styles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/291)
> Governance v2

- dapps/governance/src/modules/Dashboard/Pos/LockModal.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.css
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
- dapps/governance/src/store/lockDays&blockNumber.ts
- packages/common/components/showPopup/Modal/index.tsx
- packages/common/components/showPopup/Toast/index.tsx
-Rewritten the calculation of lock-up time.
-Optimize tips for insufficient ticket rights.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/293)
> fix: Rewrite lock calculation, Insufficient votes prompt

- dapps/governance/src/components/TipModal/index.tsx
- dapps/governance/src/modules/Dashboard/Statistics/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
- dapps/governance/src/store/proposalList.ts
-fix some issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/296)
> fix: UI, proposals title, blank image

- dapps/bridge/src/modules/data.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/301)
> Remove shuttleflow

- dapps/bridge/src/modules/data.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/302)
> fix: sf path

- dapps/bridge/src/modules/data.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/303)
> bridge: reset token

- dapps/shuttle-flow/src/pages/App.js
- dapps/shuttle-flow/src/pages/components/Header/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/306)
> feat: reset shuttleflow.io modify

- dapps/governance/src/store/lockDays&blockNumber.ts
-Fixed multiple pool issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/311)
> fix: multiple pospool

- dapps/governance/src/store/rewardInterestRate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/313)
> fix: storagePointProp calc

- dapps/governance/src/store/rewardInterestRate.ts
Remove redundant code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/315)
> Dev detach governance v2

- dapps/shuttle-flow/src/pages/App.js
- dapps/shuttle-flow/src/pages/components/Header/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/321)
> feat: remove shuttleflow

- dapps/governance/src/store/pos.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/324)
> Fix bug shine

- dapps/cross-space/src/modules/ESpace2Core/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/327)
> fix(cross-space): eSpace->core balance symbol error

- dapps/cross-space/src/components/TokenList/TokenListDropdown.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/330)
> feat: show success toast after add token to mm

- dapps/airdrop/package.json
- dapps/bridge/package.json
- dapps/bsc-espace/package.json
- dapps/cross-space/package.json
- dapps/dapp-box/package.json
- dapps/etc-espace/package.json
- dapps/governance/package.json
- dapps/payment/package.json
- dapps/pos/package.json
- packages/common/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/331)
> fix: use-wallet-react version upgrade

- packages/common/modules/Navbar/WalletConnector/ConnectorDropdown.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/340)
> fix: Navbar account display

- dapps/governance/src/modules/Vote/RewardInterestRate/VotingResult.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/339)
> fix: gov eSpace metamask AuthEspace style

- dapps/dapp-box/index.html
- dapps/dapp-box/src/App.css
- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/345)
> fix: hub mainLayout px

- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/346)
> feat: Add ban voting logic

- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/348)
> fix: core space isESpaceLock

- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/349)
> merge inner 8888

- dapps/governance/src/store/contracts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/351)
> feat: gov eSpace main contract

- dapps/governance/src/modules/Vote/RewardInterestRate/CastVotesModal/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/353)
> fix: voteValue maybe '0'

- dapps/bridge/package.json
- dapps/bsc-espace/package.json
- dapps/cross-space/package.json
- dapps/etc-espace/package.json
- dapps/governance/package.json
- dapps/payment/package.json
- dapps/pos/package.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/363)
> fix: Lock the react-hook-form version and remove shuttle-flow

- dapps/airdrop/package.json
- dapps/bridge/package.json
- dapps/bsc-espace/package.json
- dapps/cross-space/package.json
- dapps/dapp-box/package.json
- dapps/etc-espace/package.json
- dapps/governance/package.json
- dapps/payment/package.json
- dapps/pos/package.json
- packages/common/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/365)
> fix: update use-wallet-react

- dapps/airdrop/package.json
- dapps/bridge/package.json
- dapps/bsc-espace/package.json
- dapps/cross-space/package.json
- dapps/dapp-box/package.json
- dapps/etc-espace/package.json
- dapps/governance/package.json
- dapps/payment/package.json
- dapps/pos/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/376)
> fix: revert custom-react-scrollbar version

- dapps/dapp-box/src/App.tsx
- packages/common/modules/Navbar/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/383)
> fix: Determine NavbarVisible

- dapps/shuttle-flow/src/constants/chainConfig.js
- packages/common/conf/Networks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/385)
> fix: change scanurl to .org

- dapps/airdrop/src/modules/index.tsx
- dapps/governance/src/modules/Dashboard/Statistics/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/389)
> fix: update validator url

- dapps/airdrop/src/modules/index.tsx
- dapps/governance/src/modules/Dashboard/Statistics/index.tsx
- dapps/governance/src/modules/Vote/RewardInterestRate/VotingResult.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/392)
> Merge stage into main

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/393)
> fix: build remove shuttleflow

- dapps/dapp-box/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/396)
> build: fixed vite version

- dapps/governance/src/modules/PowStake/Lock/LockModal.tsx
- dapps/governance/src/store/proposalList.ts
- packages/common/utils/time.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-dapps/400)
> fix: reversed calRemainTime
